services:
  - type: web
    name: bestbuy-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m playwright install --with-deps
    startCommand: python monitor.py
